version: '3.9'

services:
  keycloak:
    build: ./infrastructure/keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./infrastructure/keycloak/realm-export.json:/opt/keycloak/realm-export.json
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]
    networks:
      - myapp-network

  auth-service:
    build: ./services/auth
    env_file:
      - ./services/auth/.env
    depends_on:
      - keycloak
    ports:
      - "3001:3001"
    networks:
      - myapp-network

  user-service:
    build: ./services/user
    env_file:
      - ./services/user/.env
    depends_on:
      - keycloak
    ports:
      - "3002:3002"
    networks:
      - myapp-network

  notification-service:
    build: ./services/notification
    env_file:
      - ./services/notification/.env
    depends_on:
      - keycloak
    ports:
      - "3003:3003"
    networks:
      - myapp-network

  gateway:
    build: ./services/gateway
    env_file:
      - ./services/gateway/.env
    ports:
      - "3000:3000"
    depends_on:
      - keycloak
      - auth-service
      - user-service
      - notification-service
    networks:
      - myapp-network

  client-app:
    build:
      context: ./apps/client
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
    networks:
      - myapp-network
    depends_on:
      - gateway
      - keycloak

  admin-panel:
    build:
      context: ./apps/admin
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    networks:
      - myapp-network
    depends_on:
      - gateway
      - keycloak

volumes:
  keycloak_data:

networks:
  myapp-network:
    driver: bridge
