
services:
  admin-panel:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile.dev
    restart: always  
    volumes:
      - ./apps/admin:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # useful for file watching inside Docker on some OS

#   client:
#     build:
#       context: ./apps/client
#       dockerfile: Dockerfile.dev
#     volumes:
#       - ./apps/client:/app
#       - /app/node_modules
#     environment:
#       - NODE_ENV=development
#     ports:
#       - "3000:3000"
#     networks:
#       - myapp-network
#     depends_on:
#       - gateway

#   admin:
#     build:
#       context: ./apps/admin
#       dockerfile: Dockerfile.dev
#     volumes:
#       - ./apps/admin:/admin
#       - /admin/node_modules
#     environment:
#       - NODE_ENV=development
#       - CHOKIDAR_USEPOLLING=true
#     ports:
#       - "5173:5173"
#     command: >
#       sh -c "corepack enable && corepack prepare pnpm@9.15.2 --activate &&
#       pnpm install && pnpm dev --host 0.0.0.0 --port 5173"
#     networks:
#       - myapp-network
#     depends_on:
#       - gateway

#   auth:
#     build:
#       context: ./services/auth
#       dockerfile: Dockerfile.dev
#     volumes:
#       - ./services/auth:/app
#       - /app/node_modules
#     env_file:
#       - ./services/auth/.env
#     networks:
#       - myapp-network
#     depends_on:
#       - keycloak

#   user:
#     build:
#       context: ./services/user
#       dockerfile: Dockerfile.dev
#     volumes:
#       - ./services/user:/app
#       - /app/node_modules
#     env_file:
#       - ./services/user/.env
#     networks:
#       - myapp-network
#     depends_on:
#       - keycloak

#   notification:
#     build:
#       context: ./services/notification
#       dockerfile: Dockerfile.dev
#     volumes:
#       - ./services/notification:/app
#       - /app/node_modules
#     env_file:
#       - ./services/notification/.env
#     networks:
#       - myapp-network
#     depends_on:
#       - keycloak

#   gateway:
#     build:
#       context: ./services/gateway
#       dockerfile: Dockerfile.dev
#     volumes:
#       - ./services/gateway:/app
#       - /app/node_modules
#     env_file:
#       - ./services/gateway/.env
#     networks:
#       - myapp-network
#     depends_on:
#       - auth
#       - user
#       - notification

# networks:
#   myapp-network:
#     external: true
